[package]
name = "listener_udp"
description = "UDP listener for whisper-net"
version = "0.1.0"
edition = "2025"
author = "ratgang"
license = "Apache-2.0"

[dependencies]
alsa = "0.9.1"
crossbeam = "0.8.4"
